// Measures the bottom around every spot from NOAA NCEI's coastal elevation model
// (CUDEM, 1/9 arc-second, about 3 m) and writes the DEPTH table into index.html.
//
//   node tools/compute-depth.js            # sample NCEI, update index.html
//   node tools/compute-depth.js --dry      # print the table, change nothing
//
// For each spot, a grid every 25 m out to 300 m is sampled. Water cells are those below
// 0 m NAVD88. Recorded, in feet: the depth at the spot, the typical (median) depth
// around it, and the deep water nearby (mean of the deepest 5% of cells) with its
// distance and bearing. Relief = deep - typical: how much a hole or channel drops below
// the water around it. Depths are relative to NAVD88, close to mean water on this coast,
// so they read roughly as depth at mid tide; relief does not depend on the datum.
'use strict';
const fs = require('fs');
const path = require('path');

const HTML = path.join(__dirname, '..', 'index.html');
const SERVICE = 'https://gis.ngdc.noaa.gov/arcgis/rest/services/DEM_mosaics/DEM_all/ImageServer/getSamples';
const RADIUS_M = 300, STEP_M = 25, FT = 3.28084;
const DRY = process.argv.includes('--dry');

const html = fs.readFileSync(HTML, 'utf8');
const a = html.indexOf('const SPOTS = [');
const fetchStart = html.indexOf('/* FETCH:BEGIN');
const SPOTS = new Function(html.slice(a, fetchStart) + ';return SPOTS;')();

async function samples(points){
  const body = new URLSearchParams({
    geometry: JSON.stringify({points, spatialReference:{wkid:4326}}),
    geometryType: 'esriGeometryMultipoint', returnFirstValueOnly: 'true',
    interpolation: 'RSP_NearestNeighbor', f: 'json'
  });
  let lastErr;
  for(let attempt = 0; attempt < 4; attempt++){
    try{
      const r = await fetch(SERVICE, {method:'POST', body});
      const j = await r.json();
      if(j.error) throw new Error(JSON.stringify(j.error));
      return j.samples.map(s => +s.value);
    }catch(e){ lastErr = e; await new Promise(r => setTimeout(r, 3000 * (attempt + 1))); }
  }
  throw lastErr;
}

const COMPASS = ['N','NNE','NE','ENE','E','ESE','SE','SSE','S','SSW','SW','WSW','W','WNW','NW','NNW'];

async function depthFor(spot){
  const ky = 111320, kx = 111320 * Math.cos(spot.lat * Math.PI / 180);
  const cells = [];
  const n = Math.round(RADIUS_M / STEP_M);
  for(let i = -n; i <= n; i++) for(let j = -n; j <= n; j++){
    const dx = j * STEP_M, dy = i * STEP_M;
    if(Math.hypot(dx, dy) > RADIUS_M) continue;
    cells.push({dx, dy, lon: spot.lon + dx / kx, lat: spot.lat + dy / ky});
  }
  const vals = await samples(cells.map(c => [c.lon, c.lat]));
  cells.forEach((c, k) => { c.z = vals[k]; });
  const water = cells.filter(c => Number.isFinite(c.z) && c.z < 0);
  const at = cells.find(c => c.dx === 0 && c.dy === 0);
  if(water.length < 20) return {waterCells: water.length};
  const depths = water.map(c => -c.z * FT).sort((p, q) => p - q);
  const median = depths[Math.floor(depths.length / 2)];
  const top = water.slice().sort((p, q) => p.z - q.z).slice(0, Math.max(3, Math.ceil(water.length * 0.05)));
  const deep = top.reduce((s, c) => s - c.z * FT, 0) / top.length;
  const cx = top.reduce((s, c) => s + c.dx, 0) / top.length, cy = top.reduce((s, c) => s + c.dy, 0) / top.length;
  const bearing = (Math.atan2(cx, cy) * 180 / Math.PI + 360) % 360;
  return {
    waterCells: water.length,
    at: at && at.z < 0 ? +(-at.z * FT).toFixed(1) : null,
    median: +median.toFixed(1), deep: +deep.toFixed(1), relief: +(deep - median).toFixed(1),
    dist: Math.round(Math.hypot(cx, cy)), dir: COMPASS[Math.round(bearing / 22.5) % 16]
  };
}

(async () => {
  const rows = [];
  for(const s of SPOTS){
    const d = await depthFor(s);
    rows.push({id:s.id, ...d});
    console.log(s.id.padEnd(20), d.median == null ? `too little water (${d.waterCells} cells)` :
      `at ${String(d.at ?? 'bank').padStart(5)} ft  typical ${String(d.median).padStart(5)}  deep ${String(d.deep).padStart(5)}  relief ${String(d.relief).padStart(5)}  ${d.dist} m ${d.dir}`);
  }
  if(DRY) return;
  const table = rows.map(r => r.median == null ? `  ${JSON.stringify(r.id)}:null,`
    : `  ${JSON.stringify(r.id)}:{at:${r.at}, typical:${r.median}, deep:${r.deep}, relief:${r.relief}, dist:${r.dist}, dir:"${r.dir}"},`).join('\n');
  const block = `/* DEPTH:BEGIN — generated by tools/compute-depth.js from NOAA NCEI CUDEM; do not edit by hand.
   Feet below NAVD88 (about mean water) within ${RADIUS_M} m of each spot. relief = deep - typical. */
const DEPTH = {
${table}
};
/* DEPTH:END */
`;
  const cur = fs.readFileSync(HTML, 'utf8');
  const ds = cur.indexOf('/* DEPTH:BEGIN');
  let out;
  if(ds >= 0){
    const de = cur.indexOf('/* DEPTH:END */') + '/* DEPTH:END */\n'.length;
    out = cur.slice(0, ds) + block + cur.slice(de);
  }else{
    const fe = cur.indexOf('/* FETCH:END */') + '/* FETCH:END */\n'.length;
    out = cur.slice(0, fe) + block + cur.slice(fe);
  }
  fs.writeFileSync(HTML, out);
  console.log(`\nWrote DEPTH for ${rows.length} spots.`);
})().catch(e => { console.error(e); process.exit(1); });
